car_sales:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('RDS_PG_HOST') }}"
      port: "{{ env_var('RDS_PG_PORT') | int }}"
      user: "{{ env_var('RDS_PG_USER') }}"
      password: "{{ env_var('RDS_PG_PASSWORD') }}"
      dbname: "{{ env_var('RDS_PG_DATABASE') }}"
      schema: staging
      threads: 4
